# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: gjnail.Heft
PackageVersion: 1.0.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: heft.exe
  PortableCommandAlias: heft
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/gjnail/heft/releases/download/v1.0.1/heft-1.0.1-windows-x86_64.zip
  InstallerSha256: 907CC677A84CB558EF7836183A084DDD3709F64D187FFFEFDD6A9A6DED397959
ManifestType: installer
ManifestVersion: 1.12.0
