# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: gjnail.Heft
PackageVersion: 1.1.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: heft.exe
  PortableCommandAlias: heft
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/gjnail/heft/releases/download/v1.1.0/heft-1.1.0-windows-x86_64.zip
  InstallerSha256: 0C573115308ADFC7709A5B3EC3A8C42D0A996252F9FCFF8CB6645F74E8BF872E
ManifestType: installer
ManifestVersion: 1.12.0
